name: markdownlint
description: Run markdownlint-cli2

runs:
  using: composite
  steps:
    - name: Checkout sources
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup Bun
      uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1.2.2

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile

    - name: Lint markdown
      shell: bash
      run: bunx markdownlint-cli2 "**/*.md" "**/*.mdx"